spring:
  datasource:
    url: jdbc:mysql://localhost:3306/room_service
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: HikariCP
      maximum-pool-size: 10
    dialect: org.hibernate.dialect.MySQL8Dialect
  jpa:
    hibernate:
      ddl-auto: update  # options: none, update, create, create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
   
  application: 
     name: ROOM-SERVICE
        
server:
  port: 8082
  
  eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # URL of the Eureka Server
    fetch-registry: true                          # Fetch the registry from the Eureka server
    register-with-eureka: true                    # Register this application with Eureka server
  instance:
    instance-id: ${spring.application.name}:${server.port} # Unique instance ID
    prefer-ip-address: true                        # Use IP address instead of hostname

# Logging configuration (optional)
  level:
    com.netflix.eureka: DEBUG